plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.arcoordinate'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.arcoordinate'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.ar:core:1.33.0'
}
